export const COMMAND_HELP = [
  "cc-bridge commands:",
  "/start",
  "/help",
  "/doctor",
  "/new codex [cwd]",
  "/new claude [cwd]",
  "/sessions",
  "/switch <id>",
  "/resume <id>",
  "/fork <id>",
  "/stop",
  "/status",
  "/keyboard",
  "/raw <text>",
  "/send <text>",
  "/cwd",
  "/cwd <value>",
  "/files",
  "",
  "normal text is forwarded to the active session with Enter.",
].join("\n");
